import type { StrategyResult, StrategySummary } from '../api'

const labels: Record<string, string> = {
  backend: '执行引擎', asset_types: '适用资产', timeframes: '周期', entry_signals: '买入信号', exit_signals: '卖出信号',
  matching: '成交时点', entry_fill: '买入价格', exit_fill: '卖出价格', minute_fill: '分钟成交', stop_loss: '止损', take_profit: '止盈',
  trailing_stop: '移动止损', trailing_take_profit_activate: '移动止盈启动', trailing_take_profit_drawdown: '移动止盈回撤', max_hold_days: '最长持有天数',
}
const percent = (value: number | null) => value == null ? '—' : `${(value * 100).toFixed(2)}%`
export function StrategyDetail({ strategy, results, onClose }: { strategy: StrategySummary; results: Partial<Record<'3m' | '6m' | '12m', StrategyResult>>; onClose: () => void }) {
  return <div className="fixed inset-0 z-[100] flex items-end justify-center overflow-y-auto overscroll-contain bg-black/70 p-0 sm:items-center sm:p-5" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}>
    <section role="dialog" aria-modal="true" aria-label={`${strategy.name} 详细说明`} className="flex max-h-[92vh] max-h-[92dvh] w-full max-w-4xl flex-col overflow-hidden rounded-t-2xl border border-border bg-card shadow-xl sm:rounded-2xl">
      <div className="flex shrink-0 items-start justify-between gap-4 border-b border-border p-5 sm:p-7"><div className="min-w-0"><p className="text-xs uppercase tracking-wide text-muted">策略档案 · {strategy.source || '内置策略'}</p><h2 className="mt-1 text-xl font-semibold">{strategy.name}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">{strategy.description || '暂无说明'}</p></div><button type="button" aria-label="关闭详情" onClick={onClose} className="shrink-0 rounded-lg border px-3 py-2 text-sm">关闭</button></div>
      <div data-dialog-content className="min-h-0 overflow-y-auto overscroll-contain p-5 sm:p-7">
      <div className="mt-6 grid gap-6 lg:grid-cols-2"><section><h3 className="font-semibold">策略规则</h3>{strategy.rules?.length ? <ul className="mt-2 list-inside list-disc space-y-1 text-sm leading-6">{strategy.rules.map((rule, index) => <li key={index}>{typeof rule === 'string' ? rule : JSON.stringify(rule)}</li>)}</ul> : <p className="mt-2 rounded-lg bg-base p-3 text-sm text-muted">源码未单独声明规则文本。下方展示该策略实际配置的信号和筛选项，不对源码作推测。</p>}
        <h3 className="mt-5 font-semibold">买卖信号</h3><DetailRow label="买入信号" value={strategy.entry_signals} /><DetailRow label="卖出信号" value={strategy.exit_signals} /><DetailRow label="基础筛选" value={strategy.basic_filter} /></section>
        <section><h3 className="font-semibold">执行与风控</h3><div className="mt-2 grid grid-cols-1 gap-2 sm:grid-cols-2">{Object.entries(strategy.execution ?? {}).map(([key, value]) => <DetailRow key={key} label={labels[key] ?? key} value={value} />)}{(['stop_loss', 'take_profit', 'trailing_stop', 'trailing_take_profit_activate', 'trailing_take_profit_drawdown', 'max_hold_days'] as const).map(key => <DetailRow key={key} label={labels[key]} value={strategy[key]} percent={key !== 'max_hold_days'} />)}</div></section></div>
      <section className="mt-6"><h3 className="font-semibold">参数与评分</h3><div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(strategy.params ?? []).map((param, index) => <div key={String(param.id ?? index)} className="rounded-lg bg-base p-3 text-sm"><div className="font-medium">{String(param.label ?? param.id ?? '参数')}</div><div className="mt-1 text-xs text-muted">默认 {String(strategy.params_defaults?.[String(param.id)] ?? param.default ?? '—')} · {String(param.description ?? param.type ?? '')}</div></div>)}{Object.entries(strategy.scoring ?? {}).map(([key, value]) => <div key={key} className="rounded-lg bg-base p-3 text-sm"><div className="font-medium">评分 · {key}</div><div className="mt-1 text-xs text-muted">{JSON.stringify(value)} · 方向 {strategy.scoring_directions?.[key] ?? '—'}</div></div>)}</div>{!strategy.params?.length && !Object.keys(strategy.scoring ?? {}).length && <p className="mt-2 text-sm text-muted">未声明可展示的参数或评分项。</p>}</section>
      <section className="mt-6"><h3 className="font-semibold">回测记录</h3><div className="mt-2 grid gap-2 md:grid-cols-3">{(['3m', '6m', '12m'] as const).map(period => { const result = results[period]; return <div key={period} className="rounded-lg border p-3"><h4 className="text-sm font-medium">{period === '3m' ? '最近三个月' : period === '6m' ? '最近半年' : '最近一年'}</h4><p className="mt-1 text-xs text-muted">请求区间：{result?.actual_start ?? '—'} 至 {result?.actual_end ?? '—'}</p>{result ? <div className="mt-2 grid grid-cols-2 gap-2 text-xs"><Metric label="总收益" value={percent(result.total_return)} /><Metric label="最大回撤" value={percent(result.max_drawdown)} /><Metric label="基准收益" value={percent(result.benchmark_return)} /><Metric label="超额收益" value={percent(result.excess_return)} /><Metric label="胜率" value={percent(result.win_rate)} /><Metric label="夏普" value={result.sharpe?.toFixed(2) ?? '—'} /><Metric label="盈亏比" value={result.profit_factor?.toFixed(2) ?? '—'} /><Metric label="交易数" value={result.trade_count?.toString() ?? '—'} /></div> : <p className="mt-2 text-sm text-muted">暂无结果</p>}{result?.status !== 'completed' && result?.reason && <p className="mt-2 text-xs text-amber-600">{result.reason}</p>}{result?.updated_at && <p className="mt-2 text-[10px] text-muted">更新于 {result.updated_at} · 配置 {result.config_fingerprint?.slice(0, 10) ?? '—'} · 源码 {result.source_fingerprint?.slice(0, 10) ?? '—'}</p>}</div> })}</div></section>
      </div>
    </section>
  </div>
}
function DetailRow({ label, value, percent: isPercent = false }: { label: string; value: unknown; percent?: boolean }) { const display = Array.isArray(value) ? value.join('、') || '—' : value && typeof value === 'object' ? JSON.stringify(value) : value == null || value === '' ? '—' : isPercent && typeof value === 'number' ? `${(value * 100).toFixed(2)}%` : String(value); return <div className="min-w-0 rounded-lg bg-base px-3 py-2"><div className="text-[10px] text-muted">{label}</div><div className="mt-0.5 break-all text-sm">{display}</div></div> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded bg-base p-2"><div className="text-[10px] text-muted">{label}</div><div className="mt-0.5 font-semibold tabular-nums">{value}</div></div> }
